version: "3.9"

services:
  sadpanda:
    build: .
    container_name: sadpanda
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
      STREAMLIT_SERVER_PORT: "8501"
      STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
    ports:
      - "8501:8501"
    volumes:
      - ./config.json:/app/config.json
      - ./dashboard.db:/app/dashboard.db
      - ./thumbnails:/app/thumbnails
      - /mnt/seagate4tb:/mnt/seagate4tb
    restart: unless-stopped
